### ISSUE TITLE
Create Add Comic Page

### ISSUE THREAD

**Issue by imran-mid** [imran-mid/Hearth-Tale-v2#7]
##### Related Issue --> #5 
# 
## Tasks
- [ ] Complete #5 
- [ ] Implement form/ JS page
- [ ] Create Firestore collection for comics
- [ ] Update Firestore DB rules to allow access to collection
- [ ] Link form to firstore
- [ ] Test read, write access

### Refs: 
See project [Figma](https://www.figma.com/proto/nEnGH8CuoWSkCzJw3QNnpe/HearthTale?node-id=665%3A578&starting-point-node-id=634%3A132&scaling=scale-down) for design
