### ISSUE TITLE
Update home page view to now include comic cards in a 'swipeable' container

### ISSUE THREAD

**Issue by imran-mid** [imran-mid/Hearth-Tale-v2#8]
# Tasks
- [ ] Create new comic view card
- [ ] Refactor story card: have a 'home' function which shows the 2 views using a swipeable container
- [ ] Fetch data from firebase like we do stories (related to #7 )
- [ ] Update documentation

## Refs
See [Figma](https://www.figma.com/proto/nEnGH8CuoWSkCzJw3QNnpe/HearthTale?node-id=653%3A69&starting-point-node-id=634%3A132&scaling=scale-down)
